### PR TITLE
Homepage

### PR DESCRIPTION
**Pull request by kingdemon24**

### CODE REVIEW

**Comment by kingdemon24** [comment]
completed

**Review by KryssNa — CHANGES_REQUESTED** [review]
need some changes except that all fine

**Review by KryssNa — APPROVED** [review]
all done

**Review by haxor09alert — APPROVED** [review]
reviewed

**Comment by haxor09alert** [comment]
reviewed

**Comment by haxor09alert** [comment]
reviewewd

**Pull request merged**
