### PR TITLE
Trip plan

### PR DESCRIPTION
**Pull request by KryssNa**

### CODE REVIEW

**Review by KryssNa — COMMENTED** [review]
all good

**Review by Jemnish — APPROVED** [review]
Good

**Review by haxor09alert — APPROVED** [review]

**Comment by haxor09alert** [comment]
dchecked

**Comment by KryssNa** [comment]
your branch have conflict need to solve it before merging

**Comment by Jemnish** [comment]
resolved conflicts @KryssNa

**Review by Jemnish — APPROVED** [review]

**Review by kingdemon24 — APPROVED** [review]
done

**Pull request merged**
