### PR TITLE
Add products

### PR DESCRIPTION
**Pull request by Jemnish**
finished

### CODE REVIEW

**Comment by KryssNa** [comment]
solve conflict

**Review by KryssNa — CHANGES_REQUESTED** [review]
file name pattern milena 
AddProduct 
ProductRepositeries


should be in camelcase 

gradle file lai ignore hanne commit nagara

**Review by Jemnish — COMMENTED** [review]
Done review

**Review by KryssNa — APPROVED** [review]
All files checked. Able to merge

**Review by kingdemon24 — APPROVED** [review]

**Comment by haxor09alert** [comment]
reviewed

**Pull request merged**
