### PR TITLE
Add place completed

### PR DESCRIPTION
**Pull request by Ayooubraj**

### CODE REVIEW

**Review by KryssNa — CHANGES_REQUESTED** [review]
validation required

**Review by KryssNa — CHANGES_REQUESTED** [review]
filename pattern doesnt match 

made changes like place_repositeries=>PlaceRepositeries 
in CamelCase

**Review by haxor09alert — APPROVED** [review]

**Review by haxor09alert — APPROVED** [review]

**Comment by Ayooubraj** [comment]
had some issues fixed the code!!

**Comment by KryssNa** [comment]
solve conflict please

**Review by KryssNa — APPROVED** [review]
checked

**Review by Jemnish — APPROVED** [review]
Good Job Ayooub

**Pull request merged**
