### PR TITLE
Admin event creation

### PR DESCRIPTION
**Pull request by kingdemon24**
Completed

### CODE REVIEW

**Review by KryssNa — CHANGES_REQUESTED** [review]
filename pattern match vayn

EvenRepositeries 

must be in CamelCase

**Comment by Jemnish** [comment]
resolve the conflict

**Review by haxor09alert — APPROVED** [review]

**Review by Jemnish — APPROVED** [review]
Good Job Biraj 👍

**Review by KryssNa — APPROVED** [review]
success and now well for testing

**Pull request merged**
