### PR TITLE
Add hotel

### PR DESCRIPTION
**Pull request by haxor09alert**

### CODE REVIEW

**Comment by haxor09alek** [comment]
fixed all the bugs

**Comment by KryssNa** [comment]
There seems to have conflict in your branch 
Please solve this conflict

**Comment by KryssNa** [comment]
Branch will be merged only after successful review of code during Spring Review

**Review by KryssNa — APPROVED** [review]
All done

**Comment by KryssNa** [comment]
✅ Add hotels merged after successful review

**Pull request merged**
